import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import Router, { useRouter } from "next/router";
import { AiFillEye, AiFillEyeInvisible } from "react-icons/ai";
import { Inter } from "@next/font/google";
import styles from "../styles/AddAnswer.module.css";
const inter = Inter({ subsets: ["latin"] });

export default function addAnswer() {
  const [bookworkCode, setBookworkCode] = useState("");
  const [answer, setAnswer] = useState("");
  const [err, setErr] = useState();
  const { query } = useRouter();

  return (
    <>
      <Head>
        <title>Sparx Maths Cheat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`bg-dark d-flex justify-content-center align-items-center flex-column ${inter.className} ${styles.main}`}
      >
        <div className={`container bg-light rounded ${styles.box}`}>
          <h1 className={`text-dark text-center`}>Add answer</h1>
          <div
            style={{
              height: 50,
            }}
          />
          <label htmlFor="username" className="form-label text-dark">
            Bookwork code:
          </label>
          <input
            type="text"
            className={`form-control form-control-lg`}
            id="username"
            onChange={(e) => setBookworkCode(e.target.value.toUpperCase())}
            value={bookworkCode}
          />
          <div
            style={{
              height: 30,
            }}
          />
          <label htmlFor="username" className="form-label text-dark">
            Answer:
          </label>
          <input
            type="text"
            className={`form-control form-control-lg`}
            id="username"
            onChange={(e) => setAnswer(e.target.value)}
            value={answer}
          />
          <div
            style={{
              height: 30,
            }}
          />

          <div
            style={{
              height: 5,
            }}
          />
          <p style={{ fontSize: "15px", color: "red" }}>{err}</p>
          <input
            type="submit"
            value="Add answer"
            className={`btn btn-lg btn-primary w-100 ${inter.className}`}
            onClick={(e) => {
              e.preventDefault();
              if (bookworkCode === "" || answer === "")
                setErr("You cannot leave any fields empty");
              else
                fetch("/api/add-answer", {
                  method: "POST",
                  body: JSON.stringify({
                    username: query.username,
                    bookworkCode: bookworkCode,
                    answer: answer,
                  }),
                })
                  .then((res) => res.json())
                  .then((res) => {
                    if (res.success)
                      Router.push(
                        {
                          pathname: "/home",
                          query: { username: query.username },
                        },
                        "/home"
                      );
                  });
            }}
          />
        </div>
      </main>
    </>
  );
}
