import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import Router from "next/router";
import { AiFillEye, AiFillEyeInvisible } from "react-icons/ai";
import { Inter } from "@next/font/google";
import styles from "../styles/Login.module.css";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [password, setPassword] = useState("");
  const [username, setUsername] = useState("");
  const [viewPassword, setViewPassword] = useState(false);
  const [err, setErr] = useState("");
  return (
    <>
      <Head>
        <title>Sparx Maths Cheat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`bg-dark d-flex justify-content-center align-items-center flex-column ${inter.className} ${styles.main}`}
      >
        <div className={`container bg-light rounded ${styles.box}`}>
          <h1 className={`text-dark text-center`}>Login</h1>
          <div
            style={{
              height: 50,
            }}
          />
          <label htmlFor="username" className="form-label text-dark">
            Username:
          </label>
          <input
            type="text"
            className={`form-control form-control-lg`}
            id="username"
            onChange={(e) => setUsername(e.target.value)}
            value={username}
          />
          <div
            style={{
              height: 30,
            }}
          />

          <label htmlFor="password" className="form-label text-dark">
            Password:
          </label>
          <div className="input-group" id="password">
            <input
              type={viewPassword ? "text" : "password"}
              className="form-control form-control-lg"
              placeholder="Password"
              onChange={(e) => setPassword(e.target.value)}
              value={password}
            />
            <button
              className="input-group-text"
              onClick={() => {
                setViewPassword(!viewPassword);
              }}
            >
              {viewPassword ? (
                <AiFillEyeInvisible style={{ fontSize: "1.25rem" }} />
              ) : (
                <AiFillEye style={{ fontSize: "1.25rem" }} />
              )}
            </button>
          </div>
          <div
            style={{
              height: 5,
            }}
          />
          <p style={{ fontSize: "15px", color: "red" }}>{err}</p>
          <input
            type="submit"
            value="Login"
            className={`btn btn-lg btn-primary w-100 ${inter.className}`}
            onClick={(e) => {
              e.preventDefault();
              if (username === "" || password === "")
                setErr("You cannot leave any fields empty");
              else
                fetch("/api/login", {
                  method: "POST",
                  body: JSON.stringify({
                    username: username,
                    password: password,
                  }),
                })
                  .then((res) => res.json())
                  .then((res) => {
                    if (res.success)
                      Router.push(
                        {
                          pathname: "/home",
                          query: { username: username },
                        },
                        "/home"
                      );
                  });
            }}
          />
          <div
            style={{
              height: 12,
            }}
          />
          <Link href={"/register"} className={`${inter.className}`}>
            Don't have an account? Click this to create one.
          </Link>
        </div>
      </main>
    </>
  );
}
